AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless service

Resources:
  <SERVICE_NAME>:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: <SERVICE_NAME>-function
      CodeUri: ./deployment/lambda.zip
      Handler: lambda.handler
      Tracing: Active
      Runtime: nodejs10.x
      AutoPublishAlias: live
      Environment:
        Variables:
          NODE_ENV: dev
          AWS_REGION: ca-central-1
  <SERVICE_NAME>-layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: <SERVICE_NAME>-layer
      Description: Sharp NPM package.
      ContentUri: './deployment/layer'
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'Available under the Apache-2.0 license.'
      RetentionPolicy: Retain