version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r1p6i7rlyflg"
s3_prefix = "sam-app-4"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
